networks:
  coltel_dev_net:
    driver: bridge

name: coltel-dev
services:
  qdrant-dev:
    image: qdrant/qdrant:v1.18.0
    ports:
      - '6335:6333' # Qdrant HTTP port
      - '6336:6334' # Qdrant gRPC port
    volumes:
      - qdrant_dev_data:/qdrant/storage
    networks:
      - coltel_dev_net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6333/healthz" ]
      interval: 5s
      timeout: 5s
      retries: 5
  postgres-dev:
    image: postgres:16.4
    ports:
      - '5435:5432'
    env_file:
      - .env.dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - coltel_dev_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5      
    restart: unless-stopped
  minio-dev:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    command: server /data --console-address ":9001"
    ports:
      - "9005:9000"
      - "9006:9001"
    env_file:
      - .env.dev
    volumes:
      - minio_dev_data:/data
    networks:
      - coltel_dev_net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis-dev:
    image: redis:7
    volumes:
      - redis_dev_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    env_file:
      - .env.dev  
    networks:
      - coltel_dev_net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
  coltel-agent-dev:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.containers.internal:host-gateway"
    command: >
      uvicorn app.main:app --host 0.0.0.0 --proxy-headers --port 8081 --reload     
    env_file:
      - .env.dev
    depends_on:
      qdrant-dev:
        condition: service_healthy
      minio-dev:
        condition: service_healthy
      postgres-dev:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - coltel_dev_net
    ports:
      - '8085:8081'
    restart: unless-stopped
  worker-dev:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    command: >
      celery -A app.celery_tasks.worker:app worker --loglevel=info     
    volumes:
      - .:/app
    networks:
      - coltel_dev_net
    depends_on:
      qdrant-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
      coltel-agent-dev:
        condition: service_started
    restart: unless-stopped
  flower-dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      celery -A app.celery_tasks.worker:app flower --port=5555 --persistent=True
    env_file:
      - .env.dev
    ports:
      - 5556:5555
    depends_on:
      - worker-dev
    networks:
      - coltel_dev_net
    restart: unless-stopped      

volumes:
  qdrant_dev_data:
  redis_dev_data:
  minio_dev_data:
  postgres_dev_data:
